### ISSUE TITLE
states output is wrong (recovered/active)

### ISSUE THREAD

**Issue by mfurlend** [ahmadawais/corona-cli#39]
Awesome script! Very cool. Seems like a bug cropped up today with the states output. I'm pretty sure it was fine yesterday.

output of `corona states`:

![image](https://user-images.githubusercontent.com/1995161/77434123-c8e2be80-6db6-11ea-8262-85e5b4a6d4b1.png)
`Active` is always 0.
`Recovered` makes no sense too.

**Comment by mfurlend** [comment]
I just realized that this is a problem with the NovelCovid API

**Comment by ahmadawais** [comment]
Yes, I have recorded that and we are looking into it.

**Comment by ahmadawais** [comment]
🐛 FIXED

🔗 https://github.com/ahmadawais/corona-cli/releases/tag/3.3.0
🔗 https://www.npmjs.com/package/corona-cli

**Comment by leanczo** [comment]
The number of recovered is still wrong and the total of others is not shown.
![Sin título](https://user-images.githubusercontent.com/50833557/78508851-626b8200-7760-11ea-808f-12e122d95867.png)
